"""12 reference architecture blueprints · Iter 74.

Per §103 Phase 6 · each blueprint declares:
  · description · use cases · mandatory components (agents · tables · endpoints · UI tabs)
  · estimated cost/time · risk level · dependencies · ADR notes

Operator selects one → API returns the full spec → Phase 7 (Marketplace)
deploys it · audited via §103 mandate.
"""
from __future__ import annotations

BLUEPRINTS = {
    "basic_rag": {
        "id": "basic_rag",
        "name": "Basic RAG",
        "category": "RAG",
        "level": 3,
        "description": "Single-source retrieval over a document corpus · TF-IDF or vector",
        "use_cases": ["FAQ", "Internal docs Q&A", "Onboarding assistant"],
        "agents": ["sys_retriever_agent", "stage_rag_layer", "stage_llm_gen"],
        "tables": ["knowledge_base", "agent_invocation", "agent_trace_event"],
        "endpoints": [
            "POST /api/v1/ril/knowledge",
            "GET  /api/v1/ril/knowledge/search?q=",
            "POST /api/v1/agentic/invoke (agent_id=stage_rag_layer)",
        ],
        "ui_tabs": ["Cross-Search", "Live Activity"],
        "estimated_setup_hours": 4,
        "estimated_monthly_cost_usd": 50,
        "risk_level": "Low",
        "dependencies": ["Postgres", "Ollama or any LLM"],
        "adr_notes": "Use Basic RAG when corpus < 10k docs and queries are short.",
    },
    "advanced_rag": {
        "id": "advanced_rag",
        "name": "Advanced RAG",
        "category": "RAG",
        "level": 4,
        "description": "Hybrid retrieval + reranking + citation enforcement + faithfulness gate",
        "use_cases": ["Customer support", "Legal research", "Compliance Q&A"],
        "agents": ["sys_retriever_agent", "stage_rag_layer", "sys_validation_agent",
                   "stage_verifier", "stage_llm_gen"],
        "tables": ["knowledge_base", "eval_registry", "golden_test_set",
                   "agent_invocation", "agent_trace_event"],
        "endpoints": [
            "POST /api/v1/agentic/invoke (multi-stage)",
            "POST /api/v1/production-pipeline/run",
            "POST /api/v1/production-pipeline/evaluate",
        ],
        "ui_tabs": ["22-Stage Production Pipeline", "Quality Scorecard"],
        "estimated_setup_hours": 16,
        "estimated_monthly_cost_usd": 250,
        "risk_level": "Medium",
        "dependencies": ["Basic RAG", "RAGAS + DeepEval libs", "eval_registry"],
        "adr_notes": "Advanced RAG required when answers need 95%+ faithfulness or citations.",
    },
    "agentic_rag": {
        "id": "agentic_rag",
        "name": "Agentic RAG",
        "category": "RAG",
        "level": 5,
        "description": "Multi-step retrieval · query planner · iterative refinement · self-review",
        "use_cases": ["Deep research", "Multi-document synthesis", "Investigation"],
        "agents": ["sys_supervisor_agent", "sys_research_agent", "sys_validation_agent",
                   "stage_planner", "stage_reflection", "stage_verifier"],
        "tables": ["knowledge_base", "workflow_run", "workflow_step",
                   "checkpoint_store", "agent_invocation"],
        "endpoints": ["POST /api/v1/production-pipeline/run (severity=high)"],
        "ui_tabs": ["▶ Run Task (Tracer)", "22-Stage Production Pipeline"],
        "estimated_setup_hours": 32,
        "estimated_monthly_cost_usd": 800,
        "risk_level": "High",
        "dependencies": ["Advanced RAG", "Council of agents", "Reflection loop"],
        "adr_notes": "Agentic RAG · high cost · use for complex multi-hop queries only.",
    },
    "multi_agent": {
        "id": "multi_agent",
        "name": "Multi-Agent System",
        "category": "Agentic",
        "level": 4,
        "description": "N specialist agents · supervisor routes · validates · escalates",
        "use_cases": ["Process automation", "Operations triage", "Code review"],
        "agents": ["sys_supervisor_agent", "sys_router_agent", "sys_validation_agent",
                   "sys_compliance_agent", "stage_planner", "stage_action"],
        "tables": ["agent_registry", "agent_skill_mapping", "workflow_run",
                   "status_history", "approval_request"],
        "endpoints": [
            "POST /api/v1/agentic/invoke",
            "POST /api/v1/governance-tables/workflow-run",
        ],
        "ui_tabs": ["All Agents", "Per-Agent Admin", "Intervention (HITL)"],
        "estimated_setup_hours": 24,
        "estimated_monthly_cost_usd": 400,
        "risk_level": "Medium",
        "dependencies": ["Supervisor pattern", "12-state workflow CHECK"],
        "adr_notes": "Multi-Agent default · use when one task needs 3+ specialist agents.",
    },
    "text2sql": {
        "id": "text2sql",
        "name": "Text2SQL",
        "category": "Analytics",
        "level": 4,
        "description": "Natural language → SQL · safety gates · RLS · LIMIT enforcement",
        "use_cases": ["Self-serve analytics", "Business Q&A", "Compliance reports"],
        "agents": ["sys_text2sql_agent", "sys_validation_agent"],
        "tables": ["dataset_registry", "access_registry", "abac_policy",
                   "agent_invocation"],
        "endpoints": [
            "POST /api/v1/governance-tables/text2sql/translate",
        ],
        "ui_tabs": ["Cross-Search"],
        "estimated_setup_hours": 8,
        "estimated_monthly_cost_usd": 150,
        "risk_level": "High",
        "dependencies": ["Strong schema docs", "RLS policies", "ABAC enforcement"],
        "adr_notes": "Text2SQL safety MANDATORY · read-only + RLS + LIMIT + auto-validate.",
    },
    "copilot": {
        "id": "copilot",
        "name": "Copilot",
        "category": "Productivity",
        "level": 2,
        "description": "Suggest-and-accept pattern · inline LLM completions · per-domain",
        "use_cases": ["Code completion", "Email drafting", "Document writing"],
        "agents": ["stage_llm_gen", "stage_guardrails"],
        "tables": ["prompt_log", "agent_invocation"],
        "endpoints": ["POST /api/v1/agentic/invoke (low-latency mode)"],
        "ui_tabs": ["▶ Run Task (Tracer)"],
        "estimated_setup_hours": 6,
        "estimated_monthly_cost_usd": 100,
        "risk_level": "Low",
        "dependencies": ["LLM client", "Guardrails"],
        "adr_notes": "Copilot · suggest-only · never auto-execute · always human-in-loop.",
    },
    "knowledge_management": {
        "id": "knowledge_management",
        "name": "Knowledge Management",
        "category": "Knowledge",
        "level": 4,
        "description": "Centralized KB · curation workflow · expert review · search",
        "use_cases": ["Internal Wiki AI", "Tribal knowledge capture", "Runbook AI"],
        "agents": ["sys_research_agent", "sys_validation_agent",
                   "sys_compliance_agent"],
        "tables": ["knowledge_base", "lesson_learned", "audit_log",
                   "approval_request"],
        "endpoints": [
            "POST /api/v1/ril/knowledge",
            "POST /api/v1/ril/lessons",
            "GET  /api/v1/ril/knowledge/search?q=",
        ],
        "ui_tabs": ["Cross-Search", "Unified Registry"],
        "estimated_setup_hours": 12,
        "estimated_monthly_cost_usd": 80,
        "risk_level": "Low",
        "dependencies": ["Basic RAG", "Approval workflow"],
        "adr_notes": "Document expert review path + monthly content audit cron.",
    },
    "incident_management": {
        "id": "incident_management",
        "name": "Incident Management",
        "category": "Operations",
        "level": 6,
        "description": "Detect · triage · RCA · resolve · postmortem · lessons learned",
        "use_cases": ["Production incidents", "Security incidents", "Customer issues"],
        "agents": ["sys_incident_classifier", "sys_root_cause_analyzer",
                   "sys_recommendation_agent", "sys_supervisor_agent"],
        "tables": ["agent_incident", "incident_management", "incident_rca",
                   "incident_timeline", "incident_postmortem", "kill_switch"],
        "endpoints": [
            "POST /api/v1/ril/incident",
            "POST /api/v1/ril/rca",
            "POST /api/v1/ril/postmortem",
            "POST /api/v1/governance-registries/kill-switch/toggle",
        ],
        "ui_tabs": ["Issues & Solutions", "Governance Registries"],
        "estimated_setup_hours": 40,
        "estimated_monthly_cost_usd": 350,
        "risk_level": "High",
        "dependencies": ["Multi-Agent", "Alerting", "Approval workflow"],
        "adr_notes": "Incident Mgmt requires 24h on-call rotation + L1/L2/L3 escalation.",
    },
    "contact_center_ai": {
        "id": "contact_center_ai",
        "name": "Contact Center AI",
        "category": "Customer",
        "level": 5,
        "description": "Voice/chat tier-1 · auto-resolve · escalate to human · QA review",
        "use_cases": ["Customer support", "Sales inquiries", "Triage"],
        "agents": ["sys_intent_classifier", "stage_rag_layer",
                   "stage_action", "stage_hitl"],
        "tables": ["agent_invocation", "approval_request", "agent_feedback",
                   "audit_log"],
        "endpoints": [
            "POST /api/v1/agentic/invoke",
            "POST /api/v1/slack/ask-agent",
            "POST /api/v1/voice-ai/transcribe",
        ],
        "ui_tabs": ["▶ Run Task (Tracer)", "Intervention (HITL)"],
        "estimated_setup_hours": 60,
        "estimated_monthly_cost_usd": 1200,
        "risk_level": "High",
        "dependencies": ["Voice AI", "Multi-channel", "Tier-1/2/3 routing"],
        "adr_notes": "CSAT measurement MANDATORY · per-tier SLA tracking.",
    },
    "hr_assistant": {
        "id": "hr_assistant",
        "name": "HR Assistant",
        "category": "HR",
        "level": 4,
        "description": "Policy Q&A · leave requests · onboarding · org Q&A",
        "use_cases": ["Benefits FAQ", "Leave workflow", "Onboarding"],
        "agents": ["sys_hr_specialist", "stage_rag_layer", "sys_compliance_agent"],
        "tables": ["knowledge_base", "approval_request", "audit_log"],
        "endpoints": ["POST /api/v1/agentic/invoke"],
        "ui_tabs": ["Cross-Search", "Intervention (HITL)"],
        "estimated_setup_hours": 16,
        "estimated_monthly_cost_usd": 200,
        "risk_level": "Medium",
        "dependencies": ["Basic RAG", "Privacy controls"],
        "adr_notes": "HR data PII-class · ABAC enforced + Compliance reviewer.",
    },
    "finance_assistant": {
        "id": "finance_assistant",
        "name": "Finance Assistant",
        "category": "Finance",
        "level": 5,
        "description": "Expense queries · budget approvals · invoice processing",
        "use_cases": ["Expense reports", "Budget Q&A", "Invoice triage"],
        "agents": ["sys_finance_specialist", "sys_compliance_agent",
                   "sys_supervisor_agent"],
        "tables": ["agent_invocation", "approval_request", "cost_center",
                   "audit_log"],
        "endpoints": [
            "POST /api/v1/agentic/invoke",
            "POST /api/v1/governance-tables/workflow-run",
        ],
        "ui_tabs": ["Quality Scorecard", "Intervention (HITL)"],
        "estimated_setup_hours": 24,
        "estimated_monthly_cost_usd": 400,
        "risk_level": "High",
        "dependencies": ["RBAC", "ABAC", "ERP integration"],
        "adr_notes": "Finance · all writes need 2-person approval per §99.6.",
    },
    "compliance_assistant": {
        "id": "compliance_assistant",
        "name": "Compliance Assistant",
        "category": "Compliance",
        "level": 6,
        "description": "Policy lookup · audit support · control evidence · attestation",
        "use_cases": ["SOC2 audit", "GDPR DSAR", "Internal control review"],
        "agents": ["sys_compliance_agent", "sys_audit_chain",
                   "sys_validation_agent", "sys_supervisor_agent"],
        "tables": ["ai_policy", "audit_log", "evidence_store", "abac_policy",
                   "approval_request"],
        "endpoints": [
            "POST /api/v1/agentic/invoke",
            "GET  /api/v1/governance-registries/abac-policies",
            "GET  /api/v1/audit-log/recent",
        ],
        "ui_tabs": ["Production Checklist", "Enterprise Standard", "Governance Registries"],
        "estimated_setup_hours": 80,
        "estimated_monthly_cost_usd": 600,
        "risk_level": "High",
        "dependencies": ["Audit chain", "Evidence store", "Policy registry"],
        "adr_notes": "Compliance · evidence retention 7 years · immutable audit chain MANDATORY.",
    },
}


def all_blueprints():
    return list(BLUEPRINTS.values())


def get_blueprint(bp_id: str):
    return BLUEPRINTS.get(bp_id)


def categories():
    cats = {}
    for bp in BLUEPRINTS.values():
        cats.setdefault(bp["category"], []).append(bp["id"])
    return cats
