"""HOLY data-downloads router — per-dept downloadable sample data.

Per-dept catalog + file-serving endpoints for sample CSV/JSON/SVG files
generated by scaffold-holy-data-downloads.py.

Composes with global §38 (download events audit-rowed by tenant) +
§41.3 (tenant isolation) + §47.6 (PII redacted at sample boundary) +
§57.6 (canonical envelope) + §64.6 (before/after viz) + §66.

Endpoints:
  GET /api/v1/holy/downloads/{dept}                  — catalog (dataset list + URLs)
  GET /api/v1/holy/downloads/{dept}/{filename}       — serve a specific file
  GET /api/v1/holy/downloads/_global                 — cross-dept inventory
"""
from __future__ import annotations

import re
import time
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import FileResponse

from core.holy_audit import log_holy_access

router = APIRouter(prefix="/api/v1/holy/downloads", tags=["holy", "downloads"])

HOLY_DEPTS = [
    "digital-marketing", "customer-experience", "supply-chain", "manufacturing",
    "product-rd", "retail-operations", "sales", "finance", "hr", "procurement",
    "executive-leadership", "e-commerce", "customer-support", "engineering",
    "it-operations", "legal", "marketing", "operations", "security-operations",
]

# File-extension catalog — keep aligned with scaffolder writes.
ALLOWED_EXTENSIONS = {".csv", ".json", ".svg"}

# Per-dept dataset_id list — keep aligned with scaffolder's DEPT_DATASETS.
DEPT_DATASETS: dict[str, list[str]] = {
    "sales":         ["lead_scoring_sample", "churn_sample", "demand_forecast_sample"],
    "finance":       ["fraud_txn_sample", "cash_flow_sample", "gl_close_sample"],
    "manufacturing": ["defect_inspection_sample", "predictive_maint_sample", "oee_sample"],
}

# Locate data/samples/ root — same candidate pattern as monitoring.py.
_DATA_CANDIDATES = [
    Path("/data") / "samples",
    Path("/app/data") / "samples",
    Path(__file__).resolve().parents[2] / "data" / "samples",
]
SAMPLES_ROOT = next((p for p in _DATA_CANDIDATES if p.exists()), _DATA_CANDIDATES[-1])

# Filename regex: dataset_id is lowercase + underscores; extension limited.
# Examples ok:  lead_scoring_sample.csv,  churn_sample.before.svg
# Rejected:     ../etc/passwd,  hidden.txt,  Cap.csv,  /abs/path
FILENAME_PAT = re.compile(r"^[a-z][a-z0-9_]*(?:\.(?:before|after))?\.(?:csv|json|svg)$")


def _validate_dept(dept: str) -> None:
    if dept not in HOLY_DEPTS:
        raise HTTPException(404, f"Unknown dept '{dept}' — must be one of {len(HOLY_DEPTS)} HOLY depts")


def _datasets_for(dept: str) -> list[str]:
    """Return the dataset_id list for this dept (3 detailed or 1 generic stub)."""
    if dept in DEPT_DATASETS:
        return DEPT_DATASETS[dept]
    return [f"{dept.replace('-', '_')}_primary_sample"]


def _file_urls(dept: str, dataset_id: str) -> dict[str, str]:
    """Build the 4-file URL set per dataset."""
    base = f"/api/v1/holy/downloads/{dept}"
    return {
        "csv":         f"{base}/{dataset_id}.csv",
        "json":        f"{base}/{dataset_id}.json",
        "before_svg":  f"{base}/{dataset_id}.before.svg",
        "after_svg":   f"{base}/{dataset_id}.after.svg",
    }


# _global BEFORE /{dept} per §66.3 FastAPI greedy-match trap.
@router.get("/_global")
def global_inventory(http_request: Request) -> dict[str, Any]:
    """Cross-dept inventory — datasets + file counts."""
    log_holy_access(http_request, "downloads", "global_inventory")
    inventory = {dept: _datasets_for(dept) for dept in HOLY_DEPTS}
    n_datasets_total = sum(len(v) for v in inventory.values())
    return {
        "n_depts": len(HOLY_DEPTS),
        "depts": HOLY_DEPTS,
        "n_datasets_total": n_datasets_total,
        "n_files_total": n_datasets_total * 4,   # csv + json + before + after
        "per_dept_datasets": inventory,
        "scanned_at": time.time(),
    }


@router.get("/{dept}")
def dept_catalog(http_request: Request, dept: str) -> dict[str, Any]:
    """Per-dept catalog — datasets + per-dataset URL set."""
    _validate_dept(dept)
    log_holy_access(http_request, "downloads", "dept_catalog", dept=dept)
    datasets = _datasets_for(dept)
    return {
        "dept": dept,
        "n_datasets": len(datasets),
        "datasets": [
            {"dataset_id": did, "files": _file_urls(dept, did)}
            for did in datasets
        ],
        "scanned_at": time.time(),
    }


@router.get("/{dept}/{filename}")
def serve_file(http_request: Request, dept: str, filename: str):
    """Serve a specific dataset file. Hardened against path traversal."""
    _validate_dept(dept)

    # 1. Lexical filter — reject anything not matching the expected pattern.
    if not FILENAME_PAT.match(filename):
        raise HTTPException(
            400,
            f"Malformed filename '{filename}' (must be <dataset>[.before|.after].(csv|json|svg))"
        )

    # 2. Build target path under SAMPLES_ROOT/<dept>/ and resolve symlinks.
    base = (SAMPLES_ROOT / dept).resolve()
    target = (base / filename).resolve()

    # 3. Defense-in-depth: ensure resolved path stays within base.
    try:
        target.relative_to(base)
    except ValueError:
        raise HTTPException(400, "Path traversal attempt rejected")

    if not target.exists() or not target.is_file():
        raise HTTPException(404, f"File '{filename}' not found for dept '{dept}'")

    # All validators passed — now audit-row this access (anti-info-leak: 404 first).
    log_holy_access(http_request, "downloads", "serve_file",
                    dept=dept, extra={"filename": filename})

    # Map extension to media type
    media_type = {
        ".csv":  "text/csv",
        ".json": "application/json",
        ".svg":  "image/svg+xml",
    }[target.suffix]

    return FileResponse(
        target,
        media_type=media_type,
        filename=filename,
        headers={"Cache-Control": "public, max-age=300"},
    )
