"""KPI registry · single source of truth.

Per docs/MARKETING_KPI_FRAMEWORK.md (operator brief 2026-06-08).
85+ KPIs across 15 categories · honest "—" values per §57.7 when not
yet wired to a real data source.
"""
from __future__ import annotations

from typing import Any


# ─── Category metadata ──────────────────────────────────────────
CATEGORIES = [
    {"id": "executive",   "name": "Executive",   "weight": 0.25,
     "desc": "Revenue · ROI · CLV · CAC · Marketing Health"},
    {"id": "customer",    "name": "Customer",    "weight": 0.15,
     "desc": "Total · Active · New · Repeat · Churn · NPS"},
    {"id": "segmentation","name": "Segmentation","weight": 0.05,
     "desc": "Segment size · growth · conversion · AI accuracy"},
    {"id": "campaign",    "name": "Campaign",    "weight": 0.15,
     "desc": "Reach · impressions · CTR · conversion · ROI"},
    {"id": "email",       "name": "Email",       "weight": 0.05,
     "desc": "Delivery · open · click · bounce · unsubscribe"},
    {"id": "website",     "name": "Website",     "weight": 0.05,
     "desc": "Visitors · sessions · bounce · conversion"},
    {"id": "social",      "name": "Social Media","weight": 0.03,
     "desc": "Followers · reach · engagement · sentiment"},
    {"id": "lead",        "name": "Lead Mgmt",   "weight": 0.10,
     "desc": "MQL · SQL · conversion · quality · response time"},
    {"id": "journey",     "name": "Customer Journey","weight": 0.03,
     "desc": "Completion · drop-off · time-to-conversion · NBA accuracy"},
    {"id": "survey",      "name": "Survey",      "weight": 0.04,
     "desc": "Response rate · NPS · CSAT · CES · sentiment"},
    {"id": "advertising", "name": "Advertising", "weight": 0.03,
     "desc": "CPC · CPM · CPA · ROAS · quality score"},
    {"id": "loyalty",     "name": "Loyalty",     "weight": 0.03,
     "desc": "Members · redemption · retention · tier upgrades"},
    {"id": "financial",   "name": "Financial",   "weight": 0.05,
     "desc": "Spend · budget · revenue · margin · CLV/CAC"},
    {"id": "ai",          "name": "AI Performance","weight": 0.10,
     "desc": "Model accuracy · adoption · cost · trust · drift"},
    {"id": "governance",  "name": "Governance",  "weight": 0.05,
     "desc": "Consent · PII · audit · policy · bias · explainability"},
]
# Weights from operator's scorecard map to the 8-category aggregator:
# Revenue Impact (25%) → executive · Customer Growth (15%) → customer ·
# Campaign Performance (15%) → campaign · Customer Experience (10%) →
# survey + journey + social · Lead Management (10%) → lead ·
# Operational Excellence (10%) → email + website + advertising ·
# AI Performance (10%) → ai + segmentation · Governance (5%) → governance


# ─── KPI registry ──────────────────────────────────────────────
# Schema: {id, category, name, formula, target, unit, source, status}
# status: 'live' (wired to data) · 'scaffolded' (registry-only) · 'planned'
KPIS: list[dict[str, Any]] = [
    # 1. Executive
    {"id": "exec.marketing_roi", "category": "executive", "name": "Marketing ROI",
     "formula": "(Revenue - Cost) / Cost", "target_op": ">", "target": 3.0,
     "unit": "ratio", "source": "marketing_campaigns + cost ledger", "status": "scaffolded"},
    {"id": "exec.revenue_generated", "category": "executive", "name": "Revenue Generated",
     "formula": "SUM(campaign_revenue)", "target_op": "growth", "target": None,
     "unit": "USD", "source": "marketing_campaign_runs.outcome_score × value", "status": "scaffolded"},
    {"id": "exec.cac", "category": "executive", "name": "Customer Acquisition Cost",
     "formula": "Cost / New Customers", "target_op": "<", "target": 100.0,
     "unit": "USD", "source": "spend ledger / new_customers", "status": "scaffolded"},
    {"id": "exec.clv", "category": "executive", "name": "Customer Lifetime Value",
     "formula": "AVG(Lifetime Revenue per Customer)", "target_op": ">", "target": 500.0,
     "unit": "USD", "source": "voice_ai_customers + transactions", "status": "scaffolded"},
    {"id": "exec.marketing_contribution", "category": "executive", "name": "Marketing Contribution",
     "formula": "Marketing Revenue / Total Revenue", "target_op": ">", "target": 0.35,
     "unit": "ratio", "source": "attribution model", "status": "planned"},
    {"id": "exec.cost_per_lead", "category": "executive", "name": "Cost Per Lead",
     "formula": "Spend / Leads", "target_op": "<", "target": 50.0,
     "unit": "USD", "source": "spend / leads count", "status": "scaffolded"},
    {"id": "exec.cpa", "category": "executive", "name": "Cost Per Acquisition",
     "formula": "Spend / Acquisitions", "target_op": "<", "target": 200.0,
     "unit": "USD", "source": "spend / converted count", "status": "scaffolded"},
    {"id": "exec.roas", "category": "executive", "name": "Return On Ad Spend",
     "formula": "Revenue / Ad Spend", "target_op": ">", "target": 4.0,
     "unit": "ratio", "source": "ad spend ledger", "status": "planned"},
    {"id": "exec.pipeline_contribution", "category": "executive", "name": "Pipeline Contribution",
     "formula": "Marketing-Sourced Pipeline / Total Pipeline", "target_op": ">", "target": 0.40,
     "unit": "ratio", "source": "pipeline ledger", "status": "planned"},
    {"id": "exec.revenue_attribution", "category": "executive", "name": "Revenue Attribution",
     "formula": "SUM(attributed_revenue)", "target_op": "growth", "target": None,
     "unit": "USD", "source": "multi-touch attribution", "status": "planned"},

    # 2. Customer
    {"id": "cust.total", "category": "customer", "name": "Total Customers",
     "formula": "COUNT(voice_ai_customers)", "target_op": "growth", "target": None,
     "unit": "count", "source": "voice_ai_customers", "status": "live"},
    {"id": "cust.active", "category": "customer", "name": "Active Customers",
     "formula": "COUNT(active in last 30d)", "target_op": ">", "target": 0.50,
     "unit": "count", "source": "last_engaged_at < 30d", "status": "scaffolded"},
    {"id": "cust.new", "category": "customer", "name": "New Customers",
     "formula": "COUNT(created_at last 30d)", "target_op": "growth", "target": None,
     "unit": "count", "source": "master_contacts.created_at", "status": "live"},
    {"id": "cust.repeat", "category": "customer", "name": "Repeat Customers",
     "formula": "COUNT(>1 marketing_campaign_runs)", "target_op": "growth", "target": None,
     "unit": "count", "source": "marketing_campaign_runs", "status": "scaffolded"},
    {"id": "cust.churn_rate", "category": "customer", "name": "Churn Rate",
     "formula": "Churned / Active", "target_op": "<", "target": 0.05,
     "unit": "ratio", "source": "voice_ai_customers status", "status": "planned"},
    {"id": "cust.retention_rate", "category": "customer", "name": "Retention Rate",
     "formula": "1 - Churn Rate", "target_op": ">", "target": 0.95,
     "unit": "ratio", "source": "derived", "status": "planned"},
    {"id": "cust.growth_rate", "category": "customer", "name": "Customer Growth Rate",
     "formula": "(New - Churned) / Total", "target_op": ">", "target": 0.05,
     "unit": "ratio", "source": "derived", "status": "scaffolded"},
    {"id": "cust.nps", "category": "customer", "name": "NPS",
     "formula": "% Promoters - % Detractors", "target_op": ">", "target": 50.0,
     "unit": "score", "source": "marketing_campaign_runs (survey channel)", "status": "scaffolded"},
    {"id": "cust.csat", "category": "customer", "name": "CSAT",
     "formula": "AVG(satisfaction_score)", "target_op": ">", "target": 4.5,
     "unit": "score 1-5", "source": "survey responses", "status": "planned"},
    {"id": "cust.ces", "category": "customer", "name": "CES",
     "formula": "AVG(effort_score)", "target_op": "<", "target": 2.5,
     "unit": "score 1-5", "source": "survey responses", "status": "planned"},

    # 3. Segmentation
    {"id": "seg.size", "category": "segmentation", "name": "Segment Size",
     "formula": "COUNT per segment", "target_op": ">", "target": 50,
     "unit": "count", "source": "master_contacts.segment", "status": "live"},
    {"id": "seg.conversion", "category": "segmentation", "name": "Segment Conversion",
     "formula": "Converted / Targeted per segment", "target_op": ">", "target": 0.10,
     "unit": "ratio", "source": "marketing_campaign_runs", "status": "scaffolded"},
    {"id": "seg.revenue", "category": "segmentation", "name": "Segment Revenue",
     "formula": "SUM(revenue per segment)", "target_op": "growth", "target": None,
     "unit": "USD", "source": "attribution", "status": "planned"},
    {"id": "seg.ai_accuracy", "category": "segmentation", "name": "AI Segment Accuracy",
     "formula": "Predicted == Actual / Total", "target_op": ">", "target": 0.85,
     "unit": "ratio", "source": "autonomous_agent + ground truth", "status": "planned"},

    # 4. Campaign
    {"id": "camp.reach", "category": "campaign", "name": "Campaign Reach",
     "formula": "SUM(runs_created)", "target_op": "growth", "target": None,
     "unit": "count", "source": "marketing_campaign_runs", "status": "live"},
    {"id": "camp.ctr", "category": "campaign", "name": "Campaign CTR",
     "formula": "Clicks / Impressions", "target_op": ">", "target": 0.03,
     "unit": "ratio", "source": "marketing_campaign_runs status", "status": "scaffolded"},
    {"id": "camp.conversion_rate", "category": "campaign", "name": "Campaign Conversion Rate",
     "formula": "Converted / Reach", "target_op": ">", "target": 0.05,
     "unit": "ratio", "source": "marketing_campaign_runs status='converted'", "status": "live"},
    {"id": "camp.roi", "category": "campaign", "name": "Campaign ROI",
     "formula": "(Revenue - Cost) / Cost per campaign", "target_op": ">", "target": 3.0,
     "unit": "ratio", "source": "campaign cost + attribution", "status": "scaffolded"},
    {"id": "camp.completion_rate", "category": "campaign", "name": "Campaign Completion Rate",
     "formula": "Completed / Created", "target_op": ">", "target": 0.95,
     "unit": "ratio", "source": "marketing_campaigns.status", "status": "live"},

    # 5. Email
    {"id": "email.delivery_rate", "category": "email", "name": "Email Delivery Rate",
     "formula": "Delivered / Sent", "target_op": ">", "target": 0.97,
     "unit": "ratio", "source": "marketing_campaign_runs (email channel)", "status": "live"},
    {"id": "email.open_rate", "category": "email", "name": "Email Open Rate",
     "formula": "Opened / Delivered", "target_op": ">", "target": 0.25,
     "unit": "ratio", "source": "status='opened'", "status": "scaffolded"},
    {"id": "email.click_rate", "category": "email", "name": "Email Click Rate",
     "formula": "Clicked / Delivered", "target_op": ">", "target": 0.03,
     "unit": "ratio", "source": "status='clicked'", "status": "scaffolded"},
    {"id": "email.click_to_open", "category": "email", "name": "Click-to-Open",
     "formula": "Clicks / Opens", "target_op": ">", "target": 0.15,
     "unit": "ratio", "source": "derived", "status": "scaffolded"},
    {"id": "email.bounce_rate", "category": "email", "name": "Email Bounce Rate",
     "formula": "Bounced / Sent", "target_op": "<", "target": 0.02,
     "unit": "ratio", "source": "status='bounced'", "status": "scaffolded"},
    {"id": "email.unsubscribe_rate", "category": "email", "name": "Unsubscribe Rate",
     "formula": "Unsubscribed / Delivered", "target_op": "<", "target": 0.001,
     "unit": "ratio", "source": "consent_marketing transitions", "status": "scaffolded"},

    # 6. Website
    {"id": "web.visitors", "category": "website", "name": "Visitors",
     "formula": "COUNT(unique sessions)", "target_op": "growth", "target": None,
     "unit": "count", "source": "input_events + page views", "status": "planned"},
    {"id": "web.bounce_rate", "category": "website", "name": "Website Bounce Rate",
     "formula": "Single-page sessions / Total sessions", "target_op": "<", "target": 0.40,
     "unit": "ratio", "source": "input_events", "status": "planned"},
    {"id": "web.conversion_rate", "category": "website", "name": "Website Conversion Rate",
     "formula": "Goal Completions / Sessions", "target_op": ">", "target": 0.05,
     "unit": "ratio", "source": "form submissions / sessions", "status": "scaffolded"},

    # 7. Social Media
    {"id": "social.engagement_rate", "category": "social", "name": "Social Engagement Rate",
     "formula": "(Likes + Comments + Shares) / Followers", "target_op": ">", "target": 0.05,
     "unit": "ratio", "source": "content_posting_runs (social platforms)", "status": "planned"},
    {"id": "social.sentiment", "category": "social", "name": "Social Sentiment",
     "formula": "AVG(sentiment_score)", "target_op": ">", "target": 0.6,
     "unit": "score -1..1", "source": "sentiment API (deferred)", "status": "planned"},

    # 8. Lead
    {"id": "lead.generated", "category": "lead", "name": "Leads Generated",
     "formula": "COUNT(marketing_campaign_runs status in ['converted','responded'])",
     "target_op": "growth", "target": None,
     "unit": "count", "source": "marketing_campaign_runs", "status": "live"},
    {"id": "lead.conversion_rate", "category": "lead", "name": "Lead Conversion Rate",
     "formula": "Converted Leads / Total Leads", "target_op": ">", "target": 0.15,
     "unit": "ratio", "source": "derived", "status": "scaffolded"},
    {"id": "lead.quality_score", "category": "lead", "name": "Lead Quality Score",
     "formula": "AVG(quality_score on master_contacts)", "target_op": ">", "target": 0.70,
     "unit": "0..1", "source": "master_contacts.quality_score", "status": "live"},
    {"id": "lead.response_time", "category": "lead", "name": "Lead Response Time",
     "formula": "AVG(time from lead → first contact)", "target_op": "<", "target": 3600,
     "unit": "seconds", "source": "audit_row timestamps", "status": "scaffolded"},

    # 9. Journey
    {"id": "journey.completion_rate", "category": "journey", "name": "Journey Completion Rate",
     "formula": "Completed Journeys / Started", "target_op": ">", "target": 0.65,
     "unit": "ratio", "source": "campaign_schedules + executions", "status": "scaffolded"},
    {"id": "journey.drop_off", "category": "journey", "name": "Journey Drop-Off Rate",
     "formula": "Abandoned / Started", "target_op": "<", "target": 0.20,
     "unit": "ratio", "source": "derived", "status": "scaffolded"},
    {"id": "journey.time_to_conversion", "category": "journey", "name": "Time To Conversion",
     "formula": "AVG(created_at → converted_at)", "target_op": "<", "target": 172800,
     "unit": "seconds", "source": "marketing_campaign_runs", "status": "scaffolded"},
    {"id": "journey.nba_accuracy", "category": "journey", "name": "NBA Accuracy",
     "formula": "Correct NBA recommendations / Total", "target_op": ">", "target": 0.80,
     "unit": "ratio", "source": "autonomous_agent_runs decisions", "status": "planned"},

    # 10. Survey
    {"id": "survey.response_rate", "category": "survey", "name": "Survey Response Rate",
     "formula": "Responses / Sent", "target_op": ">", "target": 0.20,
     "unit": "ratio", "source": "marketing_campaign_runs (survey channel)", "status": "live"},
    {"id": "survey.nps", "category": "survey", "name": "NPS (Survey)",
     "formula": "% Promoters - % Detractors", "target_op": ">", "target": 50,
     "unit": "score", "source": "survey responses", "status": "scaffolded"},
    {"id": "survey.completion_rate", "category": "survey", "name": "Survey Completion Rate",
     "formula": "Completed / Started", "target_op": ">", "target": 0.80,
     "unit": "ratio", "source": "response_data full vs partial", "status": "scaffolded"},

    # 11. Advertising
    {"id": "ad.cpc", "category": "advertising", "name": "Cost Per Click",
     "formula": "Spend / Clicks", "target_op": "<", "target": 2.0,
     "unit": "USD", "source": "ad spend ledger", "status": "planned"},
    {"id": "ad.cpm", "category": "advertising", "name": "Cost Per Mille",
     "formula": "Spend / (Impressions / 1000)", "target_op": "<", "target": 15.0,
     "unit": "USD", "source": "ad spend ledger", "status": "planned"},
    {"id": "ad.roas", "category": "advertising", "name": "ROAS (Ads)",
     "formula": "Ad Revenue / Ad Spend", "target_op": ">", "target": 4.0,
     "unit": "ratio", "source": "ad spend + attribution", "status": "planned"},

    # 12. Loyalty
    {"id": "loyalty.gold_share", "category": "loyalty", "name": "Gold Segment Share",
     "formula": "COUNT(gold) / COUNT(all)", "target_op": ">", "target": 0.10,
     "unit": "ratio", "source": "master_contacts.segment", "status": "live"},
    {"id": "loyalty.retention", "category": "loyalty", "name": "Loyalty Retention",
     "formula": "Active Members / Total Members", "target_op": ">", "target": 0.85,
     "unit": "ratio", "source": "derived", "status": "live"},

    # 13. Financial
    {"id": "fin.marketing_spend", "category": "financial", "name": "Marketing Spend",
     "formula": "SUM(spend)", "target_op": "budget", "target": None,
     "unit": "USD", "source": "spend ledger", "status": "planned"},
    {"id": "fin.budget_utilization", "category": "financial", "name": "Budget Utilization",
     "formula": "Spend / Budget", "target_op": "<", "target": 1.0,
     "unit": "ratio", "source": "derived", "status": "planned"},
    {"id": "fin.clv_cac_ratio", "category": "financial", "name": "CLV/CAC Ratio",
     "formula": "CLV / CAC", "target_op": ">", "target": 3.0,
     "unit": "ratio", "source": "derived", "status": "scaffolded"},
    {"id": "fin.campaign_profitability", "category": "financial", "name": "Campaign Profitability",
     "formula": "(Revenue - Cost) per campaign", "target_op": ">", "target": 0,
     "unit": "USD", "source": "derived", "status": "scaffolded"},

    # 14. AI
    {"id": "ai.lead_scoring_accuracy", "category": "ai", "name": "Lead Scoring Accuracy",
     "formula": "Correct predictions / Total", "target_op": ">", "target": 0.85,
     "unit": "ratio", "source": "autonomous_agent + ground truth", "status": "planned"},
    {"id": "ai.churn_accuracy", "category": "ai", "name": "Churn Prediction Accuracy",
     "formula": "Correct churn predictions / Total", "target_op": ">", "target": 0.80,
     "unit": "ratio", "source": "planned model", "status": "planned"},
    {"id": "ai.recommendation_accuracy", "category": "ai", "name": "Recommendation Accuracy",
     "formula": "Recommended → adopted / Total recommendations",
     "target_op": ">", "target": 0.30,
     "unit": "ratio", "source": "autonomous_agent_runs.decisions", "status": "scaffolded"},
    {"id": "ai.adoption_rate", "category": "ai", "name": "AI Adoption Rate",
     "formula": "AI-driven campaigns / Total campaigns",
     "target_op": ">", "target": 0.50,
     "unit": "ratio", "source": "autonomous_agent_runs / marketing_campaigns", "status": "live"},
    {"id": "ai.cost_per_request", "category": "ai", "name": "AI Cost Per Request",
     "formula": "AI Spend / Requests", "target_op": "<", "target": 0.01,
     "unit": "USD", "source": "model ledger (planned)", "status": "planned"},
    {"id": "ai.roi", "category": "ai", "name": "AI ROI",
     "formula": "(AI-attributed Revenue - AI Cost) / AI Cost",
     "target_op": ">", "target": 5.0,
     "unit": "ratio", "source": "derived", "status": "planned"},
    {"id": "ai.trust_score", "category": "ai", "name": "AI Trust Score",
     "formula": "Survey: 'I trust AI decisions' agreement",
     "target_op": ">", "target": 0.70,
     "unit": "ratio", "source": "operator survey (planned)", "status": "planned"},
    {"id": "ai.drift_score", "category": "ai", "name": "AI Drift Score",
     "formula": "PSI / KS over feature distributions",
     "target_op": "<", "target": 0.20,
     "unit": "PSI", "source": "drift monitor (planned)", "status": "planned"},

    # 15. Governance
    {"id": "gov.consent_compliance", "category": "governance", "name": "Consent Compliance",
     "formula": "Campaigns with valid consent / Total campaigns",
     "target_op": ">", "target": 1.0,
     "unit": "ratio", "source": "marketing_campaign_runs.consent_ok", "status": "live"},
    {"id": "gov.pii_violations", "category": "governance", "name": "PII Violation Count",
     "formula": "DLP rejections in audit period",
     "target_op": "<", "target": 5,
     "unit": "count", "source": "audit logs · dlp_ok=false", "status": "live"},
    {"id": "gov.audit_findings", "category": "governance", "name": "Audit Findings",
     "formula": "Failures in last weekly digest",
     "target_op": "<", "target": 1,
     "unit": "count", "source": "weekly digest red rows", "status": "live"},
    {"id": "gov.policy_violation_rate", "category": "governance", "name": "Policy Violation Rate",
     "formula": "Violations / Total decisions",
     "target_op": "<", "target": 0.01,
     "unit": "ratio", "source": "autonomous_agent_runs halts", "status": "live"},
    {"id": "gov.data_quality_score", "category": "governance", "name": "Data Quality Score",
     "formula": "AVG(master_contacts.quality_score)",
     "target_op": ">", "target": 0.70,
     "unit": "0..1", "source": "master_contacts.quality_score", "status": "live"},
    {"id": "gov.ai_bias_score", "category": "governance", "name": "AI Bias Score (DI)",
     "formula": "min(cohort) / max(cohort) per §76 fairness",
     "target_op": ">", "target": 0.80,
     "unit": "ratio", "source": "autonomous_agent_runs.fairness_di", "status": "live"},
    {"id": "gov.explainability_score", "category": "governance", "name": "Explainability Score",
     "formula": "Decisions with reasoning field / Total",
     "target_op": ">", "target": 1.0,
     "unit": "ratio", "source": "autonomous_agent_runs.decisions reasoning", "status": "live"},
]


# ─── Dashboard hierarchy ────────────────────────────────────
DASHBOARDS = [
    {"id": "executive", "name": "Executive",
     "audience": "Board · C-Suite",
     "kpis": ["exec.marketing_roi", "exec.revenue_generated",
              "exec.cac", "exec.clv", "exec.roas"]},
    {"id": "director", "name": "Director",
     "audience": "VP Marketing",
     "kpis": ["camp.reach", "camp.conversion_rate", "camp.roi",
              "seg.size", "seg.conversion"]},
    {"id": "manager", "name": "Manager",
     "audience": "Marketing Manager",
     "kpis": ["lead.generated", "lead.conversion_rate",
              "journey.completion_rate", "email.open_rate"]},
    {"id": "operations", "name": "Operations",
     "audience": "Ops Team",
     "kpis": ["email.delivery_rate", "email.bounce_rate",
              "social.engagement_rate", "ad.cpc"]},
    {"id": "ai", "name": "AI",
     "audience": "ML Team",
     "kpis": ["ai.adoption_rate", "ai.recommendation_accuracy",
              "ai.cost_per_request", "ai.drift_score"]},
    {"id": "governance", "name": "Governance",
     "audience": "Compliance",
     "kpis": ["gov.consent_compliance", "gov.pii_violations",
              "gov.audit_findings", "gov.ai_bias_score",
              "gov.explainability_score"]},
]


# ─── AI agents (operator's 15 + project's actual) ─────────────
AI_AGENTS = [
    {"function": "Campaign Planning",       "agent": "Campaign Planner Agent",
     "implementation": "autonomous_agent.run_agent (rule-based) · §57.7"},
    {"function": "Audience Selection",      "agent": "Segmentation Agent",
     "implementation": "marketing_campaigns segment + cohort distribution"},
    {"function": "Banner Creation",          "agent": "Creative Agent",
     "implementation": "Fooocus/ComfyUI (operator install) · stub render_payload"},
    {"function": "Email Creation",          "agent": "Content Agent",
     "implementation": "services._substitute template vars"},
    {"function": "Social Posting",          "agent": "Social Agent",
     "implementation": "content_ops/postings · linkedin/twitter adapter stubs"},
    {"function": "Lead Qualification",      "agent": "Lead Agent",
     "implementation": "lead.quality_score on master_contacts"},
    {"function": "Customer Journey",        "agent": "Journey Agent",
     "implementation": "campaign_schedules + content_postings.scheduled_for"},
    {"function": "Survey Analysis",         "agent": "Feedback Agent",
     "implementation": "campaign_metrics + cohort_distribution"},
    {"function": "Reporting",               "agent": "Analytics Agent",
     "implementation": "scripts/weekly_audit_digest.py"},
    {"function": "Compliance",              "agent": "Governance Agent",
     "implementation": "DLP scan + consent gate + RAI fairness DI"},
    {"function": "Budget Control",          "agent": "FinOps Agent",
     "implementation": "planned · spend ledger"},
    {"function": "Optimization",            "agent": "Optimization Agent",
     "implementation": "autonomous_agent decision loop"},
    {"function": "Executive Reporting",     "agent": "Executive Copilot",
     "implementation": "weekly_audit_digest · 4-tile aggregate"},
    {"function": "Forecasting",             "agent": "Prediction Agent",
     "implementation": "planned · §91 WebLLM upgrade path"},
    {"function": "Autonomous Marketing",    "agent": "Supervisor Agent",
     "implementation": "autonomous_agent_runs · 5-step decision loop"},
]


# ─── Maturity model ──────────────────────────────────────
MATURITY_LEVELS = [
    {"level": "L1", "stage": "Manual Marketing",
     "characteristics": "Human-driven campaigns",
     "this_project": "✗ surpassed"},
    {"level": "L2", "stage": "Automated Marketing",
     "characteristics": "Scheduled campaigns",
     "this_project": "✓ shipped · campaign_schedules + run_due_schedules cron"},
    {"level": "L3", "stage": "AI Assisted Marketing",
     "characteristics": "AI recommendations",
     "this_project": "🟡 partial · autonomous_agent decisions rule-based per §57.7"},
    {"level": "L4", "stage": "Predictive Marketing",
     "characteristics": "AI forecasts outcomes",
     "this_project": "⏳ planned · T4.1 LLM-driven decide_next"},
    {"level": "L5", "stage": "Autonomous Marketing",
     "characteristics": "AI executes campaigns",
     "this_project": "⏳ planned · current is manager-triggered execute"},
    {"level": "L6", "stage": "Self-Optimizing",
     "characteristics": "AI continuously improves itself",
     "this_project": "⏳ planned · requires multi-cohort fairness eval (T3.2)"},
]


# ─── Scorecard composition ────────────────────────────────
SCORECARD = [
    {"id": "revenue_impact",        "weight": 0.25, "categories": ["executive"]},
    {"id": "customer_growth",       "weight": 0.15, "categories": ["customer"]},
    {"id": "campaign_performance",  "weight": 0.15, "categories": ["campaign"]},
    {"id": "customer_experience",   "weight": 0.10, "categories": ["survey", "journey", "social"]},
    {"id": "lead_management",       "weight": 0.10, "categories": ["lead"]},
    {"id": "operational_excellence","weight": 0.10, "categories": ["email", "website", "advertising"]},
    {"id": "ai_performance",        "weight": 0.10, "categories": ["ai", "segmentation"]},
    {"id": "governance",            "weight": 0.05, "categories": ["governance"]},
]


def stats() -> dict[str, Any]:
    return {
        "total_categories": len(CATEGORIES),
        "total_kpis": len(KPIS),
        "by_status": {
            "live":       sum(1 for k in KPIS if k["status"] == "live"),
            "scaffolded": sum(1 for k in KPIS if k["status"] == "scaffolded"),
            "planned":    sum(1 for k in KPIS if k["status"] == "planned"),
        },
        "total_dashboards": len(DASHBOARDS),
        "total_ai_agents": len(AI_AGENTS),
        "total_maturity_levels": len(MATURITY_LEVELS),
        "scorecard_weight_total": sum(s["weight"] for s in SCORECARD),
    }
