"""22 enterprise AI governance domains · operator master brief 2026-06-11.

Each domain follows the standard agent pattern:
  Supervisor + Planner + Analyst + Reviewer + Validation + Approval +
  Audit + Reporting + Learning agents.

Plus a standard MCP pattern:
  Knowledge · Data · Workflow · Security · Communication · Reporting · Governance.
"""

DOMAINS = [
    {
        "id": "ai_strategy",
        "name": "AI Strategy",
        "category": "Strategic",
        "purpose": "Where is AI going? · Vision · Roadmap · Investment · Portfolio",
        "agents": ["sys_strategy_supervisor", "sys_market_intelligence",
                   "sys_competitor_agent", "sys_technology_trend_agent",
                   "sys_investment_agent", "sys_roi_agent",
                   "sys_executive_advisor"],
        "mcps": ["Financial Systems", "ERP", "Market Data", "Portfolio Systems",
                 "PMO Systems"],
        "kpis": ["AI Adoption", "ROI", "Cost Savings", "Revenue Impact",
                 "Productivity Gain", "Automation Rate"],
        "questions": [
            "Which processes should be automated?",
            "Which departments benefit most?",
            "Build vs Buy?",
            "Agentic AI vs Copilot?",
        ],
    },
    {
        "id": "ai_governance",
        "name": "AI Governance",
        "category": "Governance",
        "purpose": "Council · Policy · Standards · Decision rights",
        "agents": ["sys_governance_supervisor", "sys_policy_agent",
                   "sys_standards_agent", "sys_approval_agent",
                   "sys_audit_chain", "sys_compliance_agent"],
        "mcps": ["GRC Platform", "SharePoint", "ServiceNow",
                 "Document Management"],
        "kpis": ["Policy Coverage", "Approval Time", "Standards Compliance",
                 "Council Decisions"],
        "questions": [
            "Who approves new agents?",
            "What policies apply to this workflow?",
            "Are we following our own standards?",
        ],
    },
    {
        "id": "ai_risk",
        "name": "AI Risk",
        "category": "Risk",
        "purpose": "Identify · Score · Mitigate · Monitor risks",
        "agents": ["sys_risk_supervisor", "sys_risk_detection_agent",
                   "sys_risk_scoring_agent", "sys_risk_prediction_agent",
                   "sys_risk_mitigation_agent", "sys_compliance_agent"],
        "mcps": ["ServiceNow", "Jira", "Splunk", "GRC Systems",
                 "Security Tools"],
        "kpis": ["Open Risks", "Critical Risks", "Risk Trend",
                 "Mitigation Coverage"],
        "questions": [
            "What's our top risk this week?",
            "Are we trending toward more critical risks?",
            "What's the mitigation plan?",
        ],
    },
    {
        "id": "ai_trust",
        "name": "AI Trust",
        "category": "Quality",
        "purpose": "Why should anyone trust the answer? · Evidence · Citation · Confidence",
        "agents": ["sys_trust_supervisor", "sys_validation_agent",
                   "sys_verification_engine", "sys_citation_agent",
                   "sys_escalation_agent", "sys_audit_chain"],
        "mcps": ["SharePoint", "Policy Repository", "Knowledge Base",
                 "Document Management", "Data Catalog"],
        "kpis": ["Average Trust Score", "Citation Accuracy",
                 "Retrieval Precision", "Confidence Distribution",
                 "Verification Success"],
        "questions": [
            "Why this answer?",
            "What evidence supports it?",
            "Can the user dispute it?",
        ],
    },
    {
        "id": "ai_visibility",
        "name": "AI Visibility",
        "category": "Operations",
        "purpose": "What AI assets exist? · Who owns them? · Where are they used?",
        "agents": ["sys_visibility_supervisor", "sys_inventory_agent",
                   "sys_ownership_agent", "sys_usage_tracker"],
        "mcps": ["Agent Registry", "Model Registry", "MCP Registry",
                 "Project Registry"],
        "kpis": ["Total Agents", "Active Agents", "Active Models",
                 "Active MCPs", "Running Workflows", "Monthly Requests"],
        "questions": [
            "How many active agents do we have?",
            "Who owns this model?",
            "Where is this prompt used?",
        ],
    },
    {
        "id": "ai_monitoring",
        "name": "AI Monitoring",
        "category": "Operations",
        "purpose": "Is AI healthy · accurate · secure · delivering value?",
        "agents": ["sys_monitoring_supervisor", "sys_watchdog_agent_health",
                   "sys_watchdog_model_health", "sys_watchdog_mcp_health",
                   "sys_watchdog_workflow", "sys_alert_agent",
                   "sys_root_cause_analyzer"],
        "mcps": ["Prometheus", "Grafana", "OpenTelemetry", "Datadog", "Splunk"],
        "kpis": ["Agent Health", "Model Health", "MCP Health",
                 "Workflow Success Rate", "Hallucination Rate",
                 "Confidence Score", "Drift"],
        "questions": [
            "Is anything degrading right now?",
            "What's the failure rate this hour?",
            "Are any watchdogs flagging?",
        ],
    },
    {
        "id": "ai_reporting",
        "name": "AI Reporting",
        "category": "Operations",
        "purpose": "Executive · Technical · Governance · Security reports",
        "agents": ["sys_reporting_supervisor", "sys_executive_advisor",
                   "sys_audit_chain", "sys_compliance_agent"],
        "mcps": ["Power BI", "Tableau", "Excel", "Email"],
        "kpis": ["Reports Generated", "On-time Delivery",
                 "Stakeholder Satisfaction"],
        "questions": [
            "What did AI deliver last month?",
            "Where did money go?",
            "What's our compliance status?",
        ],
    },
    {
        "id": "ai_quality",
        "name": "AI Quality",
        "category": "Quality",
        "purpose": "Accuracy · Completeness · Consistency · Explainability",
        "agents": ["sys_quality_supervisor", "sys_validation_agent",
                   "sys_verification_engine", "sys_reflection_agent",
                   "sys_top1pct_status"],
        "mcps": ["Eval Registry", "Golden Test Set", "Knowledge Base"],
        "kpis": ["Accuracy", "Hallucination", "Reliability",
                 "User Satisfaction", "Quality Score"],
        "questions": [
            "Are we still 95%+ accurate?",
            "Are hallucinations trending down?",
            "Which agent has the worst quality?",
        ],
    },
    {
        "id": "ai_performance",
        "name": "AI Performance",
        "category": "Operations",
        "purpose": "End-to-end latency · throughput · capacity",
        "agents": ["sys_perf_supervisor", "sys_watchdog_performance",
                   "sys_capacity_agent", "sys_optimization_agent"],
        "mcps": ["Prometheus", "Grafana", "k6", "Locust"],
        "kpis": ["E2E Latency p95", "Agent Latency p95", "MCP Latency p95",
                 "Throughput", "Queue Depth"],
        "questions": [
            "Where's the bottleneck?",
            "Can we handle 2x traffic?",
            "Will we exhaust capacity this quarter?",
        ],
    },
    {
        "id": "ai_reliability",
        "name": "AI Reliability (AI SRE)",
        "category": "Operations",
        "purpose": "Health checks · failover · recovery · error budgets",
        "agents": ["sys_reliability_supervisor", "sys_health_check_agent",
                   "sys_failure_detection_agent", "sys_recovery_agent",
                   "sys_failover_agent", "sys_chaos_agent",
                   "sys_root_cause_analyzer"],
        "mcps": ["PagerDuty", "ServiceNow", "Kubernetes", "Prometheus",
                 "CloudWatch"],
        "kpis": ["Availability", "MTTR", "MTBF",
                 "SLA Attainment", "Hallucination Budget",
                 "Recovery Success Rate"],
        "questions": [
            "What's our hallucination budget burn?",
            "Have we tested failover this quarter?",
            "MTTR trending up or down?",
        ],
    },
    {
        "id": "ai_security",
        "name": "AI Security",
        "category": "Security",
        "purpose": "Auth · ABAC · PII · prompt injection · cognitive security",
        "agents": ["sys_security_supervisor", "sys_watchdog_pii",
                   "sys_watchdog_prompt_injection", "sys_access_review_agent",
                   "sys_threat_agent", "sys_incident_classifier"],
        "mcps": ["SIEM", "IAM", "WAF", "Vault", "Security Scanner"],
        "kpis": ["Failed Login", "Prompt Injection Attempts",
                 "PII Exposure", "Unauthorized Access", "Tool Abuse"],
        "questions": [
            "Any active prompt injection attempts?",
            "PII leaking anywhere?",
            "Are kill-switches healthy?",
        ],
    },
    {
        "id": "ai_compliance",
        "name": "AI Compliance (RegOps)",
        "category": "Governance",
        "purpose": "Continuous compliance · evidence · audit-ready",
        "agents": ["sys_compliance_agent", "sys_policy_agent",
                   "sys_regulation_agent", "sys_evidence_agent",
                   "sys_audit_chain", "sys_retention_agent"],
        "mcps": ["GRC Platform", "SharePoint", "ServiceNow",
                 "Document Management"],
        "kpis": ["Compliance Score", "Open Findings",
                 "Audit Readiness", "Regulatory Risks",
                 "Policy Violations", "Missing Approvals"],
        "questions": [
            "Could we survive an audit today?",
            "Where's our evidence for SOC2 CC6.2?",
            "Are any models unapproved?",
        ],
    },
    {
        "id": "ai_economics",
        "name": "AI Economics (FinOps)",
        "category": "Financial",
        "purpose": "Cost per prompt · ROI · forecast · chargeback",
        "agents": ["sys_cost_agent", "sys_finops_agent",
                   "sys_token_agent", "sys_roi_agent",
                   "sys_forecast_agent", "sys_optimization_agent"],
        "mcps": ["Azure Cost Management", "AWS Cost Explorer",
                 "GCP Billing", "ERP", "Finance System"],
        "kpis": ["Total AI Spend", "Total AI Savings", "ROI",
                 "Cost Trend", "Budget Variance",
                 "Cost Per Prompt", "Cost Per Workflow"],
        "questions": [
            "What's our cost burn?",
            "Where can we save 30% with Ollama?",
            "What's the ROI per blueprint?",
        ],
    },
    {
        "id": "ai_portfolio",
        "name": "AI Portfolio",
        "category": "Strategic",
        "purpose": "Investment · prioritization · benefits realization",
        "agents": ["sys_portfolio_supervisor", "sys_investment_agent",
                   "sys_roi_agent", "sys_risk_agent",
                   "sys_capacity_agent", "sys_benefits_agent"],
        "mcps": ["ERP", "Finance Systems", "PMO Tools", "Jira", "ServiceNow"],
        "kpis": ["Total AI Investment", "Total AI Value",
                 "Portfolio ROI", "Strategic Alignment",
                 "Projects On Track", "Delayed Projects"],
        "questions": [
            "Which projects should be accelerated?",
            "Which should be stopped?",
            "Where should we invest next?",
        ],
    },
    {
        "id": "ai_workforce",
        "name": "AI Workforce (Digital Employees)",
        "category": "Operations",
        "purpose": "Agent hire · train · certify · monitor · retire",
        "agents": ["sys_workforce_supervisor", "sys_router_agent",
                   "sys_memory_agent", "sys_cost_agent",
                   "sys_compliance_agent"],
        "mcps": ["Agent Registry", "Skill Registry", "HR Systems"],
        "kpis": ["Agent Utilization", "Agent Success Rate",
                 "Agent Cost", "Agent Quality Score",
                 "Agents Retired", "Agents Promoted"],
        "questions": [
            "Which agents are underutilized?",
            "Who's the top performer this month?",
            "Time to retire any agents?",
        ],
    },
    {
        "id": "ai_knowledge",
        "name": "AI Knowledge Management",
        "category": "Knowledge",
        "purpose": "Capture · classify · search · reuse organizational memory",
        "agents": ["sys_knowledge_supervisor", "sys_kb_seeder",
                   "sys_classification_agent", "sys_search_agent",
                   "sys_summarization_agent", "sys_lessons_learned_agent"],
        "mcps": ["SharePoint", "Confluence", "Jira", "ServiceNow",
                 "GitHub", "Teams", "Outlook", "ERP"],
        "kpis": ["Knowledge Coverage", "Reuse Rate", "Duplicate Content",
                 "Missing Knowledge", "Search Accuracy",
                 "Knowledge Freshness", "Trust Score"],
        "questions": [
            "Have we lost knowledge when people left?",
            "Are we solving the same problem twice?",
            "What lessons are getting reused?",
        ],
    },
    {
        "id": "ai_resilience",
        "name": "AI Resilience",
        "category": "Operations",
        "purpose": "Beyond DR · chaos testing · region failover · model failover",
        "agents": ["sys_resilience_supervisor", "sys_chaos_agent",
                   "sys_failover_agent", "sys_recovery_agent"],
        "mcps": ["Chaos Mesh", "LitmusChaos", "Kubernetes", "AWS"],
        "kpis": ["RTO", "RPO", "Failover Success Rate",
                 "Chaos Test Coverage", "Business Impact"],
        "questions": [
            "Have we tested region failover?",
            "What's our model failover chain?",
            "Have we run chaos this quarter?",
        ],
    },
    {
        "id": "ai_ethics",
        "name": "AI Ethics & Responsible AI",
        "category": "Governance",
        "purpose": "Bias · fairness · explainability · accountability · oversight",
        "agents": ["sys_ethics_supervisor", "sys_fairness_agent",
                   "sys_bias_agent", "sys_explainability_agent",
                   "sys_compliance_agent"],
        "mcps": ["Fairlearn", "AIF360", "SHAP", "LIME"],
        "kpis": ["Bias Score (disparate impact ≥ 0.8)",
                 "Fairness Across Groups", "Explanation Coverage",
                 "Human Override Rate"],
        "questions": [
            "Is the model fair across protected groups?",
            "Can we explain every regulated decision?",
            "Is HITL escalation tested?",
        ],
    },
    {
        "id": "ai_change_mgmt",
        "name": "AI Change Management",
        "category": "Operations",
        "purpose": "Stakeholder readiness · training · adoption · benefits realization",
        "agents": ["sys_change_supervisor", "sys_adoption_agent",
                   "sys_training_agent", "sys_communication_agent"],
        "mcps": ["Teams", "Slack", "Confluence", "Outlook"],
        "kpis": ["Stakeholder Readiness", "Training Completion",
                 "Adoption Rate", "User Satisfaction",
                 "Benefits Realization"],
        "questions": [
            "Do users trust AI?",
            "Are users over-trusting AI?",
            "What training is needed?",
        ],
    },
    {
        "id": "ai_intelligence",
        "name": "AI Intelligence (Digital Twin)",
        "category": "Strategic",
        "purpose": "Knowledge graph · predictive · scenario simulation · advisors",
        "agents": ["sys_intelligence_supervisor", "sys_executive_advisor",
                   "sys_scenario_agent", "sys_top1pct_status",
                   "sys_brutal_feedback"],
        "mcps": ["Neo4j", "GraphRAG", "Knowledge Base"],
        "kpis": ["Digital Twin Coverage", "Predictions Acted Upon",
                 "Scenarios Simulated", "Advisor Queries"],
        "questions": [
            "What's the platform like a Virtual CIO?",
            "What if traffic doubled?",
            "Which agent is most at risk?",
        ],
    },
    {
        "id": "ai_accountability",
        "name": "AI Accountability",
        "category": "Governance",
        "purpose": "RACI · owner · approver · reviewer per asset",
        "agents": ["sys_accountability_supervisor", "sys_audit_chain",
                   "sys_approval_agent", "sys_compliance_agent"],
        "mcps": ["Agent Registry", "Approval Registry", "HR Systems"],
        "kpis": ["Owner Assigned %", "Approval Coverage",
                 "Audit Coverage", "Review Coverage",
                 "Compliance Coverage"],
        "questions": [
            "Who owns this agent?",
            "Who approved it?",
            "Who's accountable when it fails?",
        ],
    },
    {
        "id": "ai_control_tower",
        "name": "AI Control Tower",
        "category": "Meta",
        "purpose": "Top-of-stack · aggregates all 21 other domains · live state",
        "agents": ["sys_supervisor_agent", "sys_top1pct_status",
                   "sys_brutal_feedback", "sys_executive_advisor"],
        "mcps": ["All other domains"],
        "kpis": ["AI Health Score (Green/Yellow/Red)",
                 "All 21-domain rollup"],
        "questions": [
            "Is the platform healthy right now?",
            "What needs executive attention this week?",
            "Where do we stand vs Top 1%?",
        ],
    },
]


def all_domains():
    return DOMAINS


def get_domain(domain_id: str):
    for d in DOMAINS:
        if d["id"] == domain_id:
            return d
    return None


def categories():
    cats = {}
    for d in DOMAINS:
        cats.setdefault(d["category"], []).append(d["id"])
    return cats
