"""20 missing offices · operator brief 2026-06-11 §104."""

OFFICES = [
    {"id": "ai_finance_office", "name": "AI Finance Office (FinOps)",
     "category": "Financial",
     "purpose": "Budget · forecast · chargeback · ROI",
     "kpis": ["Total spend", "Budget variance", "Cost per prompt", "ROI per workflow"],
     "questions": ["Where are we overspending?", "What's the ROI?", "Should we chargeback?"]},
    {"id": "ai_procurement_office", "name": "AI Procurement Office",
     "category": "Operations",
     "purpose": "Vendor onboarding · contract · evaluation",
     "kpis": ["Vendors active", "Spend by vendor", "Contract renewals", "Risk score"],
     "questions": ["Which vendor is most expensive?", "Any contracts up for renewal?"]},
    {"id": "ai_legal_office", "name": "AI Legal Office",
     "category": "Governance",
     "purpose": "Contracts · IP · regulatory obligations",
     "kpis": ["Open contracts", "Active reviews", "IP filings", "Regulatory exposure"],
     "questions": ["Are we IP-clean on this model?", "Any pending obligations?"]},
    {"id": "ai_audit_office", "name": "AI Audit Office",
     "category": "Governance",
     "purpose": "Internal audit · evidence · certification",
     "kpis": ["Audit findings open", "Evidence coverage", "Days to audit-ready"],
     "questions": ["Could we survive an audit today?", "Where's evidence missing?"]},
    {"id": "ai_records_office", "name": "AI Records & Retention Office",
     "category": "Governance",
     "purpose": "7-year retention · GDPR/HIPAA deletion · records management",
     "kpis": ["Records stored", "Records purged on schedule", "Deletion requests served"],
     "questions": ["Are we GDPR-compliant on deletion?", "Are records retained correctly?"]},
    {"id": "ai_iam_office", "name": "AI Identity & Access Office",
     "category": "Security",
     "purpose": "SSO · ABAC · workforce identity · agent identity",
     "kpis": ["Active identities", "Privileged accounts", "Access reviews completed"],
     "questions": ["Who has admin?", "Any inactive privileged accounts?"]},
    {"id": "ai_observability_office", "name": "AI Observability Office",
     "category": "Operations",
     "purpose": "OpenTelemetry · logs · traces · metrics",
     "kpis": ["Trace coverage", "Log volume", "Metric scrapes", "Alert SNR"],
     "questions": ["Can we trace this request end-to-end?", "What's the noise ratio?"]},
    {"id": "ai_platform_eng_office", "name": "AI Platform Engineering Office",
     "category": "Operations",
     "purpose": "K8s · MCP runtime · agent runtime · platform health",
     "kpis": ["Platform availability", "Deploy frequency", "Lead time"],
     "questions": ["What's the platform's DORA score?", "Any toil to automate?"]},
    {"id": "ai_sre_office", "name": "AI Reliability Engineering (AI-SRE)",
     "category": "Operations",
     "purpose": "Error budgets · failover · chaos · SLOs",
     "kpis": ["SLO attainment", "Error budget burn", "MTTR", "Chaos exercises"],
     "questions": ["Are we burning error budget?", "Is failover tested?"]},
    {"id": "ai_agent_eng_office", "name": "AI Agent Engineering Office",
     "category": "Engineering",
     "purpose": "Agent design · skills · tools · runtime",
     "kpis": ["Agents shipped", "Skills shipped", "Quality score per agent"],
     "questions": ["Which agents need refactor?", "Any duplicate skills?"]},
    {"id": "ai_prompt_eng_office", "name": "AI Prompt Engineering Office",
     "category": "Engineering",
     "purpose": "Prompt library · version · review · injection defense",
     "kpis": ["Prompts versioned", "Accuracy per prompt", "Injection attempts blocked"],
     "questions": ["Which prompts have highest accuracy?", "Any prompts unsafe?"]},
    {"id": "ai_eval_eng_office", "name": "AI Evaluation Engineering Office",
     "category": "Engineering",
     "purpose": "RAGAS · DeepEval · golden sets · regression",
     "kpis": ["Eval coverage", "Faithfulness", "Citation accuracy"],
     "questions": ["What's our hallucination rate?", "Has accuracy regressed?"]},
    {"id": "ai_hitl_office", "name": "AI Human-in-the-Loop Office",
     "category": "Operations",
     "purpose": "HITL design · escalation · queue · review",
     "kpis": ["HITL queue depth", "Review SLA", "Approval throughput"],
     "questions": ["Where's the HITL bottleneck?", "Any stale approvals?"]},
    {"id": "ai_experimentation_office", "name": "AI Experimentation Office",
     "category": "Engineering",
     "purpose": "A/B · canary · shadow eval · feature flags",
     "kpis": ["Active experiments", "Winning variants", "Time to ship"],
     "questions": ["What experiments are active?", "Any winners to roll out?"]},
    {"id": "ai_marketplace_office", "name": "AI Marketplace · Agent Store",
     "category": "Strategic",
     "purpose": "Internal app store for agents · prompts · workflows",
     "kpis": ["Catalog size", "Reuse rate", "Average rating"],
     "questions": ["What's most reused?", "Anything ready to retire?"]},
    {"id": "ai_mcp_marketplace_office", "name": "AI API & MCP Marketplace",
     "category": "Strategic",
     "purpose": "MCP discovery · contracts · vendor MCPs",
     "kpis": ["MCPs available", "MCP usage", "MCP SLA"],
     "questions": ["Which MCPs are most used?", "Any MCP with poor SLA?"]},
    {"id": "ai_knowledge_eng_office", "name": "AI Knowledge Engineering Office",
     "category": "Knowledge",
     "purpose": "KB curation · graph engineering · ontology",
     "kpis": ["KB coverage", "Graph completeness", "Search precision"],
     "questions": ["What's missing from KB?", "Any duplicate entities?"]},
    {"id": "ai_data_contracts_office", "name": "AI Data Contract Management",
     "category": "Data",
     "purpose": "Producer/consumer contracts · SLA · schema versioning",
     "kpis": ["Contracts active", "Contract breaches", "Schema versions"],
     "questions": ["Any contracts breached?", "Need to negotiate new ones?"]},
    {"id": "ai_safety_eng_office", "name": "AI Safety Engineering Office",
     "category": "Security",
     "purpose": "Cognitive security · alignment · red-team · jailbreak defense",
     "kpis": ["Red-team findings", "Jailbreak attempts", "Safety incidents"],
     "questions": ["Are we hardened against new attacks?", "Any open findings?"]},
    {"id": "ai_agentops_office", "name": "AI Agent Operations Center (AgentOps)",
     "category": "Operations",
     "purpose": "24×7 ops · runbooks · escalation · on-call",
     "kpis": ["Open incidents", "MTTR", "Runbooks coverage", "On-call rotation"],
     "questions": ["What's burning right now?", "Who's on-call?"]},
]


def all_offices():
    return OFFICES


def get_office(office_id: str):
    for o in OFFICES:
        if o["id"] == office_id:
            return o
    return None


def categories():
    cats = {}
    for o in OFFICES:
        cats.setdefault(o["category"], []).append(o["id"])
    return cats
