#!/usr/bin/env python3
"""Export Pydantic JSON schemas from agentic routers · Iter 44 · Tier-1 #5.

Walks every Pydantic BaseModel in the agentic routers, emits:
  · backend/contracts/<module>.schema.json   (JSON schema per model)
  · backend/contracts/MANIFEST.json          (index)
  · frontend/src/schemas/agentic.contracts.js  (Zod schemas matching same fields)

Operator runs this whenever a Pydantic model changes · CI verifies frontend
schemas stay in sync.
"""
import json
import logging
import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "backend"))
os.environ.setdefault("INSUR_SKIP_MIGRATIONS", "1")
os.environ.setdefault("INSUR_DISABLE_PRESIDIO", "1")
logging.disable(logging.CRITICAL)

import importlib
import inspect
from pydantic import BaseModel

ROUTER_MODULES = [
    "agentic_core.router",
    "agentic_ops.router",
    "enterprise_governance.router",
    "risk_incident_learning.router",
]

CONTRACTS_DIR = REPO / "backend/contracts"
CONTRACTS_DIR.mkdir(parents=True, exist_ok=True)
ZOD_DIR = REPO / "frontend/src/schemas"
ZOD_DIR.mkdir(parents=True, exist_ok=True)


def discover_models() -> dict[str, dict]:
    """Return {model_name: {fields: {name: {type, required, default}}}}."""
    models: dict[str, dict] = {}
    for mod_name in ROUTER_MODULES:
        try:
            mod = importlib.import_module(mod_name)
        except Exception as e:
            print(f"  ⚠ skip {mod_name}: {type(e).__name__}: {e}")
            continue
        for name, obj in inspect.getmembers(mod):
            if (inspect.isclass(obj) and issubclass(obj, BaseModel)
                    and obj is not BaseModel and obj.__module__ == mod.__name__):
                fields = {}
                for fname, finfo in obj.model_fields.items():
                    fields[fname] = {
                        "type": str(finfo.annotation),
                        "required": finfo.is_required(),
                        "default": str(finfo.default) if not finfo.is_required() else None,
                    }
                models[name] = {
                    "module": mod_name,
                    "fields": fields,
                    "field_names": sorted(fields.keys()),
                }
    return models


def py_type_to_js_zod(py_type: str) -> str:
    """Map Pydantic type string → Zod expression."""
    t = py_type.lower().strip()
    # Strip Optional wrapper
    is_opt = "| none" in t or "optional" in t
    base = t.replace("typing.optional[", "").replace("]", "")\
            .replace(" | none", "").replace("optional[", "").strip()
    if "list[" in base or base.endswith("[]"):
        inner = base.replace("list[", "").rstrip("]").strip()
        zod = f"z.array({_atom(inner)})"
    elif "dict[" in base:
        zod = "z.record(z.any())"
    elif "datetime" in base:
        zod = "z.string()"  # ISO 8601
    else:
        zod = _atom(base)
    if is_opt:
        zod += ".optional().nullable()"
    return zod


def _atom(base: str) -> str:
    base = base.strip().lower()
    if base in ("str", "string"): return "z.string()"
    if base in ("int", "integer"): return "z.number().int()"
    if base in ("float", "decimal"): return "z.number()"
    if base in ("bool", "boolean"): return "z.boolean()"
    if "any" in base: return "z.any()"
    if "datetime" in base: return "z.string()"
    return "z.any()"


def write_contracts(models: dict[str, dict]) -> None:
    # Per-model JSON schema
    manifest = {"models": {}, "generated_at_iter": 44, "note": "Auto · do not edit"}
    for name, info in models.items():
        out = CONTRACTS_DIR / f"{name}.schema.json"
        out.write_text(json.dumps({
            "name": name, "module": info["module"], "fields": info["fields"],
        }, indent=2))
        manifest["models"][name] = {
            "module": info["module"],
            "n_fields": len(info["fields"]),
            "field_names": info["field_names"],
        }
    (CONTRACTS_DIR / "MANIFEST.json").write_text(json.dumps(manifest, indent=2))


def write_zod_schemas(models: dict[str, dict]) -> None:
    lines = [
        "// Auto-generated by scripts/export_pydantic_schemas.py · DO NOT EDIT.",
        "// Iter 44 · Tier-1 #5 · contract tests Pydantic ↔ frontend.",
        "//",
        "// Source of truth: backend/contracts/*.schema.json",
        "// Run: ./scripts/insur contracts  to regenerate.",
        "",
        "import { z } from 'zod';",
        "",
    ]
    for name in sorted(models.keys()):
        info = models[name]
        lines.append(f"// from {info['module']}")
        lines.append(f"export const {name}Schema = z.object({{")
        for fname, fmeta in info["fields"].items():
            zod = py_type_to_js_zod(fmeta["type"])
            if not fmeta["required"] and ".optional()" not in zod:
                zod += ".optional()"
            lines.append(f"  {fname}: {zod},")
        lines.append("});")
        lines.append(f"export const {name}_fields = {json.dumps(info['field_names'])};")
        lines.append("")

    lines.append("// Verification: every backend Pydantic model has a Zod schema below.")
    lines.append(f"export const PYDANTIC_MODEL_NAMES = {json.dumps(sorted(models.keys()))};")
    (ZOD_DIR / "agentic.contracts.js").write_text("\n".join(lines))


def main() -> int:
    print("Discovering Pydantic models...")
    models = discover_models()
    print(f"  ✓ found {len(models)} models")
    for name, info in sorted(models.items()):
        print(f"    {name}  ({info['module']}, {len(info['fields'])} fields)")

    write_contracts(models)
    print(f"  ✓ wrote {len(models)} JSON schemas → backend/contracts/")
    write_zod_schemas(models)
    print(f"  ✓ wrote Zod schemas → frontend/src/schemas/agentic.contracts.js")
    return 0


if __name__ == "__main__":
    sys.exit(main())
